---@class Udagawanight
---@field config UdagawanightConfig
---@field palette UdagawanightPalette
local Udagawanight = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class UdagawanightConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field contrast Contrast?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Udagawanight.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

---@class UdagawanightPalette
Udagawanight.palette = {
  dark0_hard = "#2a2f34",
  dark0 = "#343b40",
  dark0_soft = "#3f484d",
  dark1 = "#495156",
  dark2 = "#5a6267",
  dark3 = "#70777b",
  dark4 = "#8b9093",
  light0_hard = "#f5e6d3",
  light0 = "#E9E9E9",
  light0_soft = "#f4dcc4",
  light1 = "#DDDDDD",
  light2 = "#AAAAAA",
  light3 = "#717171",
  light4 = "#444444",
  -- red
  bright_red = "#B07475",
  neutral_red = "#B07475",
  faded_red = "#B07475",
  dark_red_hard = "#B07475",
  dark_red = "#B07475",
  dark_red_soft = "#B07475",
  light_red_hard = "#ffa5a5",
  light_red = "#ff9d9d",
  light_red_soft = "#f49191",
  -- green
  bright_green = "#a3d9a5",
  neutral_green = "#a1c4a3",
  faded_green = "#88aa88",
  dark_green_hard = "#5b7357",
  dark_green = "#667d61",
  dark_green_soft = "#6e8469",
  light_green_hard = "#cce6c5",
  light_green = "#d4e7cc",
  light_green_soft = "#ddebd3",
  -- yellow
  bright_yellow = "#BCC371",
  neutral_yellow = "#9B8C64",
  faded_yellow = "#ABA87B",
  -- blue
  bright_blue = "#7190C3",
  neutral_blue = "#647E9B",
  faded_blue = "#7B8DAB",
  -- purple
  bright_purple = "#d49ede",
  neutral_purple = "#c285c2",
  faded_purple = "#a974a4",
  -- aqua
  bright_aqua = "#9ad8c0",
  neutral_aqua = "#84c5ab",
  faded_aqua = "#6ea28c",
  dark_aqua_hard = "#4b6457",
  dark_aqua = "#57705e",
  dark_aqua_soft = "#617869",
  light_aqua_hard = "#cee9d8",
  light_aqua = "#d6eddc",
  light_aqua_soft = "#e0f0e2",
  -- orange
  bright_orange = "#C38771",
  neutral_orange = "#9B7364",
  faded_orange = "#AB887B",
  -- gray
  gray = "#a4a8ac",
}

local function get_colors()
  local p = Udagawanight.palette
  local config = Udagawanight.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local bg = vim.o.background
  local contrast = config.contrast

  local color_groups = {
    dark = {
      bg0 = p.dark0,
      bg1 = p.dark1,
      bg2 = p.dark2,
      bg3 = p.dark3,
      bg4 = p.dark4,
      fg0 = p.light0,
      fg1 = p.light1,
      fg2 = p.light2,
      fg3 = p.light3,
      fg4 = p.light4,
      red = p.bright_red,
      green = p.bright_green,
      yellow = p.bright_yellow,
      blue = p.bright_blue,
      purple = p.bright_purple,
      aqua = p.bright_aqua,
      orange = p.bright_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.dark_red,
      dark_green = p.dark_green,
      dark_aqua = p.dark_aqua,
      gray = p.gray,
    },
    light = {
      bg0 = p.light0,
      bg1 = p.light1,
      bg2 = p.light2,
      bg3 = p.light3,
      bg4 = p.light4,
      fg0 = p.dark0,
      fg1 = p.dark1,
      fg2 = p.dark2,
      fg3 = p.dark3,
      fg4 = p.dark4,
      red = p.faded_red,
      green = p.faded_green,
      yellow = p.faded_yellow,
      blue = p.faded_blue,
      purple = p.faded_purple,
      aqua = p.faded_aqua,
      orange = p.faded_orange,
      neutral_red = p.neutral_red,
      neutral_green = p.neutral_green,
      neutral_yellow = p.neutral_yellow,
      neutral_blue = p.neutral_blue,
      neutral_purple = p.neutral_purple,
      neutral_aqua = p.neutral_aqua,
      dark_red = p.light_red,
      dark_green = p.light_green,
      dark_aqua = p.light_aqua,
      gray = p.gray,
    },
  }

  if contrast ~= nil and contrast ~= "" then
    color_groups[bg].bg0 = p[bg .. "0_" .. contrast]
    color_groups[bg].dark_red = p[bg .. "_red_" .. contrast]
    color_groups[bg].dark_green = p[bg .. "_green_" .. contrast]
    color_groups[bg].dark_aqua = p[bg .. "_aqua_" .. contrast]
  end

  return color_groups[bg]
end

local function get_groups()
  local colors = get_colors()
  local config = Udagawanight.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg4,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  local groups = {
    UdagawanightFg0 = { fg = colors.fg0 },
    UdagawanightFg1 = { fg = colors.fg1 },
    UdagawanightFg2 = { fg = colors.fg2 },
    UdagawanightFg3 = { fg = colors.fg3 },
    UdagawanightFg4 = { fg = colors.fg4 },
    UdagawanightGray = { fg = colors.gray },
    UdagawanightBg0 = { fg = colors.bg0 },
    UdagawanightBg1 = { fg = colors.bg1 },
    UdagawanightBg2 = { fg = colors.bg2 },
    UdagawanightBg3 = { fg = colors.bg3 },
    UdagawanightBg4 = { fg = colors.bg4 },
    UdagawanightRed = { fg = colors.red },
    UdagawanightRedBold = { fg = colors.red, bold = config.bold },
    UdagawanightGreen = { fg = colors.green },
    UdagawanightGreenBold = { fg = colors.green, bold = config.bold },
    UdagawanightYellow = { fg = colors.yellow },
    UdagawanightYellowBold = { fg = colors.yellow, bold = config.bold },
    UdagawanightBlue = { fg = colors.blue },
    UdagawanightBlueBold = { fg = colors.blue, bold = config.bold },
    UdagawanightPurple = { fg = colors.purple },
    UdagawanightPurpleBold = { fg = colors.purple, bold = config.bold },
    UdagawanightAqua = { fg = colors.aqua },
    UdagawanightAquaBold = { fg = colors.aqua, bold = config.bold },
    UdagawanightOrange = { fg = colors.orange },
    UdagawanightOrangeBold = { fg = colors.orange, bold = config.bold },
    UdagawanightRedSign = config.transparent_mode and { fg = colors.red, reverse = config.invert_signs }
      or { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightGreenSign = config.transparent_mode and { fg = colors.green, reverse = config.invert_signs }
      or { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightYellowSign = config.transparent_mode and { fg = colors.yellow, reverse = config.invert_signs }
      or { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightBlueSign = config.transparent_mode and { fg = colors.blue, reverse = config.invert_signs }
      or { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightPurpleSign = config.transparent_mode and { fg = colors.purple, reverse = config.invert_signs }
      or { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightAquaSign = config.transparent_mode and { fg = colors.aqua, reverse = config.invert_signs }
      or { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightOrangeSign = config.transparent_mode and { fg = colors.orange, reverse = config.invert_signs }
      or { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    UdagawanightRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    UdagawanightGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    UdagawanightYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    UdagawanightBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    UdagawanightPurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    UdagawanightAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    UdagawanightOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "UdagawanightBg2" },
    SpecialKey = { link = "UdagawanightFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "UdagawanightPurple" },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    WinBar = { fg = colors.fg4, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg3, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg3, bg = nil } or { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "UdagawanightGreenBold" },
    Title = { link = "UdagawanightGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "UdagawanightYellowBold" },
    ModeMsg = { link = "UdagawanightYellowBold" },
    Question = { link = "UdagawanightOrangeBold" },
    WarningMsg = { link = "UdagawanightRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "UdagawanightOrange" },
    Comment = { fg = colors.gray, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "UdagawanightRed" },
    Conditional = { link = "UdagawanightRed" },
    Repeat = { link = "UdagawanightRed" },
    Label = { link = "UdagawanightRed" },
    Exception = { link = "UdagawanightRed" },
    Operator = { fg = colors.orange, italic = config.italic.operators },
    Keyword = { link = "UdagawanightRed" },
    Identifier = { link = "UdagawanightBlue" },
    Function = { link = "UdagawanightGreenBold" },
    PreProc = { link = "UdagawanightAqua" },
    Include = { link = "UdagawanightAqua" },
    Define = { link = "UdagawanightAqua" },
    Macro = { link = "UdagawanightAqua" },
    PreCondit = { link = "UdagawanightAqua" },
    Constant = { link = "UdagawanightPurple" },
    Character = { link = "UdagawanightPurple" },
    String = { fg = colors.green, italic = config.italic.strings },
    Boolean = { link = "UdagawanightPurple" },
    Number = { link = "UdagawanightPurple" },
    Float = { link = "UdagawanightPurple" },
    Type = { link = "UdagawanightYellow" },
    StorageClass = { link = "UdagawanightOrange" },
    Structure = { link = "UdagawanightAqua" },
    Typedef = { link = "UdagawanightYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.dark_red },
    DiffAdd = { bg = colors.dark_green },
    DiffChange = { bg = colors.dark_aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "UdagawanightBlueUnderline" },
    SpellBad = { link = "UdagawanightRedUnderline" },
    SpellLocal = { link = "UdagawanightAquaUnderline" },
    SpellRare = { link = "UdagawanightPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    Delimiter = { link = "UdagawanightOrange" },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "UdagawanightRed" },
    DiagnosticSignError = { link = "UdagawanightRedSign" },
    DiagnosticUnderlineError = { link = "UdagawanightRedUnderline" },
    DiagnosticWarn = { link = "UdagawanightYellow" },
    DiagnosticSignWarn = { link = "UdagawanightYellowSign" },
    DiagnosticUnderlineWarn = { link = "UdagawanightYellowUnderline" },
    DiagnosticInfo = { link = "UdagawanightBlue" },
    DiagnosticSignInfo = { link = "UdagawanightBlueSign" },
    DiagnosticUnderlineInfo = { link = "UdagawanightBlueUnderline" },
    DiagnosticHint = { link = "UdagawanightAqua" },
    DiagnosticSignHint = { link = "UdagawanightAquaSign" },
    DiagnosticUnderlineHint = { link = "UdagawanightAquaUnderline" },
    DiagnosticFloatingError = { link = "UdagawanightRed" },
    DiagnosticFloatingWarn = { link = "UdagawanightOrange" },
    DiagnosticFloatingInfo = { link = "UdagawanightBlue" },
    DiagnosticFloatingHint = { link = "UdagawanightAqua" },
    DiagnosticVirtualTextError = { link = "UdagawanightRed" },
    DiagnosticVirtualTextWarn = { link = "UdagawanightYellow" },
    DiagnosticVirtualTextInfo = { link = "UdagawanightBlue" },
    DiagnosticVirtualTextHint = { link = "UdagawanightAqua" },
    DiagnosticOk = { link = "UdagawanightGreenSign" },
    LspReferenceRead = { link = "UdagawanightYellowBold" },
    LspReferenceText = { link = "UdagawanightYellowBold" },
    LspReferenceWrite = { link = "UdagawanightOrangeBold" },
    LspCodeLens = { link = "UdagawanightGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "UdagawanightGreen" },
    gitcommitDiscardedFile = { link = "UdagawanightRed" },
    GitSignsAdd = { link = "UdagawanightGreen" },
    GitSignsChange = { link = "UdagawanightOrange" },
    GitSignsDelete = { link = "UdagawanightRed" },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.dark3 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "UdagawanightRedSign" },
    StartifyBracket = { link = "UdagawanightFg3" },
    StartifyFile = { link = "UdagawanightFg1" },
    StartifyNumber = { link = "UdagawanightBlue" },
    StartifyPath = { link = "UdagawanightGray" },
    StartifySlash = { link = "UdagawanightGray" },
    StartifySection = { link = "UdagawanightYellow" },
    StartifySpecial = { link = "UdagawanightBg2" },
    StartifyHeader = { link = "UdagawanightOrange" },
    StartifyFooter = { link = "UdagawanightBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "UdagawanightAqua" },
    DirvishArg = { link = "UdagawanightYellow" },
    netrwDir = { link = "UdagawanightAqua" },
    netrwClassify = { link = "UdagawanightAqua" },
    netrwLink = { link = "UdagawanightGray" },
    netrwSymLink = { link = "UdagawanightFg1" },
    netrwExe = { link = "UdagawanightYellow" },
    netrwComment = { link = "UdagawanightGray" },
    netrwList = { link = "UdagawanightBlue" },
    netrwHelpCmd = { link = "UdagawanightAqua" },
    netrwCmdSep = { link = "UdagawanightFg3" },
    netrwVersion = { link = "UdagawanightGreen" },
    NERDTreeDir = { link = "UdagawanightAqua" },
    NERDTreeDirSlash = { link = "UdagawanightAqua" },
    NERDTreeOpenable = { link = "UdagawanightOrange" },
    NERDTreeClosable = { link = "UdagawanightOrange" },
    NERDTreeFile = { link = "UdagawanightFg1" },
    NERDTreeExecFile = { link = "UdagawanightYellow" },
    NERDTreeUp = { link = "UdagawanightGray" },
    NERDTreeCWD = { link = "UdagawanightGreen" },
    NERDTreeHelp = { link = "UdagawanightFg1" },
    NERDTreeToggleOn = { link = "UdagawanightGreen" },
    NERDTreeToggleOff = { link = "UdagawanightRed" },
    CocErrorSign = { link = "UdagawanightRedSign" },
    CocWarningSign = { link = "UdagawanightOrangeSign" },
    CocInfoSign = { link = "UdagawanightBlueSign" },
    CocHintSign = { link = "UdagawanightAquaSign" },
    CocErrorFloat = { link = "UdagawanightRed" },
    CocWarningFloat = { link = "UdagawanightOrange" },
    CocInfoFloat = { link = "UdagawanightBlue" },
    CocHintFloat = { link = "UdagawanightAqua" },
    CocDiagnosticsError = { link = "UdagawanightRed" },
    CocDiagnosticsWarning = { link = "UdagawanightOrange" },
    CocDiagnosticsInfo = { link = "UdagawanightBlue" },
    CocDiagnosticsHint = { link = "UdagawanightAqua" },
    CocSelectedText = { link = "UdagawanightRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "UdagawanightGray" },
    CocErrorHighlight = { link = "UdagawanightRedUnderline" },
    CocWarningHighlight = { link = "UdagawanightOrangeUnderline" },
    CocInfoHighlight = { link = "UdagawanightBlueUnderline" },
    CocHintHighlight = { link = "UdagawanightAquaUnderline" },
    TelescopeNormal = { link = "UdagawanightFg1" },
    TelescopeSelection = { link = "UdagawanightOrangeBold" },
    TelescopeSelectionCaret = { link = "UdagawanightRed" },
    TelescopeMultiSelection = { link = "UdagawanightGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "UdagawanightBlue" },
    TelescopePromptPrefix = { link = "UdagawanightRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "UdagawanightFg0" },
    CmpItemAbbrDeprecated = { link = "UdagawanightFg1" },
    CmpItemAbbrMatch = { link = "UdagawanightBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "UdagawanightBlueUnderline" },
    CmpItemMenu = { link = "UdagawanightGray" },
    CmpItemKindText = { link = "UdagawanightOrange" },
    CmpItemKindVariable = { link = "UdagawanightOrange" },
    CmpItemKindMethod = { link = "UdagawanightBlue" },
    CmpItemKindFunction = { link = "UdagawanightBlue" },
    CmpItemKindConstructor = { link = "UdagawanightYellow" },
    CmpItemKindUnit = { link = "UdagawanightBlue" },
    CmpItemKindField = { link = "UdagawanightBlue" },
    CmpItemKindClass = { link = "UdagawanightYellow" },
    CmpItemKindInterface = { link = "UdagawanightYellow" },
    CmpItemKindModule = { link = "UdagawanightBlue" },
    CmpItemKindProperty = { link = "UdagawanightBlue" },
    CmpItemKindValue = { link = "UdagawanightOrange" },
    CmpItemKindEnum = { link = "UdagawanightYellow" },
    CmpItemKindOperator = { link = "UdagawanightYellow" },
    CmpItemKindKeyword = { link = "UdagawanightPurple" },
    CmpItemKindEvent = { link = "UdagawanightPurple" },
    CmpItemKindReference = { link = "UdagawanightPurple" },
    CmpItemKindColor = { link = "UdagawanightPurple" },
    CmpItemKindSnippet = { link = "UdagawanightGreen" },
    CmpItemKindFile = { link = "UdagawanightBlue" },
    CmpItemKindFolder = { link = "UdagawanightBlue" },
    CmpItemKindEnumMember = { link = "UdagawanightAqua" },
    CmpItemKindConstant = { link = "UdagawanightOrange" },
    CmpItemKindStruct = { link = "UdagawanightYellow" },
    CmpItemKindTypeParameter = { link = "UdagawanightYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "UdagawanightOrange" },
    diffNewFile = { link = "UdagawanightYellow" },
    diffOldFile = { link = "UdagawanightOrange" },
    diffLine = { link = "UdagawanightBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "UdagawanightBlue" },
    NavicIconsModule = { link = "UdagawanightOrange" },
    NavicIconsNamespace = { link = "UdagawanightBlue" },
    NavicIconsPackage = { link = "UdagawanightAqua" },
    NavicIconsClass = { link = "UdagawanightYellow" },
    NavicIconsMethod = { link = "UdagawanightBlue" },
    NavicIconsProperty = { link = "UdagawanightAqua" },
    NavicIconsField = { link = "UdagawanightPurple" },
    NavicIconsConstructor = { link = "UdagawanightBlue" },
    NavicIconsEnum = { link = "UdagawanightPurple" },
    NavicIconsInterface = { link = "UdagawanightGreen" },
    NavicIconsFunction = { link = "UdagawanightBlue" },
    NavicIconsVariable = { link = "UdagawanightPurple" },
    NavicIconsConstant = { link = "UdagawanightOrange" },
    NavicIconsString = { link = "UdagawanightGreen" },
    NavicIconsNumber = { link = "UdagawanightOrange" },
    NavicIconsBoolean = { link = "UdagawanightOrange" },
    NavicIconsArray = { link = "UdagawanightOrange" },
    NavicIconsObject = { link = "UdagawanightOrange" },
    NavicIconsKey = { link = "UdagawanightAqua" },
    NavicIconsNull = { link = "UdagawanightOrange" },
    NavicIconsEnumMember = { link = "UdagawanightYellow" },
    NavicIconsStruct = { link = "UdagawanightPurple" },
    NavicIconsEvent = { link = "UdagawanightYellow" },
    NavicIconsOperator = { link = "UdagawanightRed" },
    NavicIconsTypeParameter = { link = "UdagawanightRed" },
    NavicText = { link = "UdagawanightWhite" },
    NavicSeparator = { link = "UdagawanightWhite" },
    htmlTag = { link = "UdagawanightAquaBold" },
    htmlEndTag = { link = "UdagawanightAquaBold" },
    htmlTagName = { link = "UdagawanightBlue" },
    htmlArg = { link = "UdagawanightOrange" },
    htmlTagN = { link = "UdagawanightFg1" },
    htmlSpecialTagName = { link = "UdagawanightBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "UdagawanightRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "UdagawanightAquaBold" },
    xmlEndTag = { link = "UdagawanightAquaBold" },
    xmlTagName = { link = "UdagawanightBlue" },
    xmlEqual = { link = "UdagawanightBlue" },
    docbkKeyword = { link = "UdagawanightAquaBold" },
    xmlDocTypeDecl = { link = "UdagawanightGray" },
    xmlDocTypeKeyword = { link = "UdagawanightPurple" },
    xmlCdataStart = { link = "UdagawanightGray" },
    xmlCdataCdata = { link = "UdagawanightPurple" },
    dtdFunction = { link = "UdagawanightGray" },
    dtdTagName = { link = "UdagawanightPurple" },
    xmlAttrib = { link = "UdagawanightOrange" },
    xmlProcessingDelim = { link = "UdagawanightGray" },
    dtdParamEntityPunct = { link = "UdagawanightGray" },
    dtdParamEntityDPunct = { link = "UdagawanightGray" },
    xmlAttribPunct = { link = "UdagawanightGray" },
    xmlEntity = { link = "UdagawanightRed" },
    xmlEntityPunct = { link = "UdagawanightRed" },
    clojureKeyword = { link = "UdagawanightBlue" },
    clojureCond = { link = "UdagawanightOrange" },
    clojureSpecial = { link = "UdagawanightOrange" },
    clojureDefine = { link = "UdagawanightOrange" },
    clojureFunc = { link = "UdagawanightYellow" },
    clojureRepeat = { link = "UdagawanightYellow" },
    clojureCharacter = { link = "UdagawanightAqua" },
    clojureStringEscape = { link = "UdagawanightAqua" },
    clojureException = { link = "UdagawanightRed" },
    clojureRegexp = { link = "UdagawanightAqua" },
    clojureRegexpEscape = { link = "UdagawanightAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "UdagawanightFg3" },
    clojureAnonArg = { link = "UdagawanightYellow" },
    clojureVariable = { link = "UdagawanightBlue" },
    clojureMacro = { link = "UdagawanightOrange" },
    clojureMeta = { link = "UdagawanightYellow" },
    clojureDeref = { link = "UdagawanightYellow" },
    clojureQuote = { link = "UdagawanightYellow" },
    clojureUnquote = { link = "UdagawanightYellow" },
    cOperator = { link = "UdagawanightPurple" },
    cppOperator = { link = "UdagawanightPurple" },
    cStructure = { link = "UdagawanightOrange" },
    pythonBuiltin = { link = "UdagawanightOrange" },
    pythonBuiltinObj = { link = "UdagawanightOrange" },
    pythonBuiltinFunc = { link = "UdagawanightOrange" },
    pythonFunction = { link = "UdagawanightAqua" },
    pythonDecorator = { link = "UdagawanightRed" },
    pythonInclude = { link = "UdagawanightBlue" },
    pythonImport = { link = "UdagawanightBlue" },
    pythonRun = { link = "UdagawanightBlue" },
    pythonCoding = { link = "UdagawanightBlue" },
    pythonOperator = { link = "UdagawanightRed" },
    pythonException = { link = "UdagawanightRed" },
    pythonExceptions = { link = "UdagawanightPurple" },
    pythonBoolean = { link = "UdagawanightPurple" },
    pythonDot = { link = "UdagawanightFg3" },
    pythonConditional = { link = "UdagawanightRed" },
    pythonRepeat = { link = "UdagawanightRed" },
    pythonDottedName = { link = "UdagawanightGreenBold" },
    cssBraces = { link = "UdagawanightBlue" },
    cssFunctionName = { link = "UdagawanightYellow" },
    cssIdentifier = { link = "UdagawanightOrange" },
    cssClassName = { link = "UdagawanightGreen" },
    cssColor = { link = "UdagawanightBlue" },
    cssSelectorOp = { link = "UdagawanightBlue" },
    cssSelectorOp2 = { link = "UdagawanightBlue" },
    cssImportant = { link = "UdagawanightGreen" },
    cssVendor = { link = "UdagawanightFg1" },
    cssTextProp = { link = "UdagawanightAqua" },
    cssAnimationProp = { link = "UdagawanightAqua" },
    cssUIProp = { link = "UdagawanightYellow" },
    cssTransformProp = { link = "UdagawanightAqua" },
    cssTransitionProp = { link = "UdagawanightAqua" },
    cssPrintProp = { link = "UdagawanightAqua" },
    cssPositioningProp = { link = "UdagawanightYellow" },
    cssBoxProp = { link = "UdagawanightAqua" },
    cssFontDescriptorProp = { link = "UdagawanightAqua" },
    cssFlexibleBoxProp = { link = "UdagawanightAqua" },
    cssBorderOutlineProp = { link = "UdagawanightAqua" },
    cssBackgroundProp = { link = "UdagawanightAqua" },
    cssMarginProp = { link = "UdagawanightAqua" },
    cssListProp = { link = "UdagawanightAqua" },
    cssTableProp = { link = "UdagawanightAqua" },
    cssFontProp = { link = "UdagawanightAqua" },
    cssPaddingProp = { link = "UdagawanightAqua" },
    cssDimensionProp = { link = "UdagawanightAqua" },
    cssRenderProp = { link = "UdagawanightAqua" },
    cssColorProp = { link = "UdagawanightAqua" },
    cssGeneratedContentProp = { link = "UdagawanightAqua" },
    javaScriptBraces = { link = "UdagawanightFg1" },
    javaScriptFunction = { link = "UdagawanightAqua" },
    javaScriptIdentifier = { link = "UdagawanightRed" },
    javaScriptMember = { link = "UdagawanightBlue" },
    javaScriptNumber = { link = "UdagawanightPurple" },
    javaScriptNull = { link = "UdagawanightPurple" },
    javaScriptParens = { link = "UdagawanightFg3" },
    typescriptReserved = { link = "UdagawanightAqua" },
    typescriptLabel = { link = "UdagawanightAqua" },
    typescriptFuncKeyword = { link = "UdagawanightAqua" },
    typescriptIdentifier = { link = "UdagawanightOrange" },
    typescriptBraces = { link = "UdagawanightFg1" },
    typescriptEndColons = { link = "UdagawanightFg1" },
    typescriptDOMObjects = { link = "UdagawanightFg1" },
    typescriptAjaxMethods = { link = "UdagawanightFg1" },
    typescriptLogicSymbols = { link = "UdagawanightFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "UdagawanightFg1" },
    typescriptParens = { link = "UdagawanightFg3" },
    typescriptOpSymbols = { link = "UdagawanightFg3" },
    typescriptHtmlElemProperties = { link = "UdagawanightFg1" },
    typescriptNull = { link = "UdagawanightPurple" },
    typescriptInterpolationDelimiter = { link = "UdagawanightAqua" },
    purescriptModuleKeyword = { link = "UdagawanightAqua" },
    purescriptModuleName = { link = "UdagawanightFg1" },
    purescriptWhere = { link = "UdagawanightAqua" },
    purescriptDelimiter = { link = "UdagawanightFg4" },
    purescriptType = { link = "UdagawanightFg1" },
    purescriptImportKeyword = { link = "UdagawanightAqua" },
    purescriptHidingKeyword = { link = "UdagawanightAqua" },
    purescriptAsKeyword = { link = "UdagawanightAqua" },
    purescriptStructure = { link = "UdagawanightAqua" },
    purescriptOperator = { link = "UdagawanightBlue" },
    purescriptTypeVar = { link = "UdagawanightFg1" },
    purescriptConstructor = { link = "UdagawanightFg1" },
    purescriptFunction = { link = "UdagawanightFg1" },
    purescriptConditional = { link = "UdagawanightOrange" },
    purescriptBacktick = { link = "UdagawanightOrange" },
    coffeeExtendedOp = { link = "UdagawanightFg3" },
    coffeeSpecialOp = { link = "UdagawanightFg3" },
    coffeeCurly = { link = "UdagawanightOrange" },
    coffeeParen = { link = "UdagawanightFg3" },
    coffeeBracket = { link = "UdagawanightOrange" },
    rubyStringDelimiter = { link = "UdagawanightGreen" },
    rubyInterpolationDelimiter = { link = "UdagawanightAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "UdagawanightRed" },
    objcDirective = { link = "UdagawanightBlue" },
    goDirective = { link = "UdagawanightAqua" },
    goConstants = { link = "UdagawanightPurple" },
    goDeclaration = { link = "UdagawanightRed" },
    goDeclType = { link = "UdagawanightBlue" },
    goBuiltins = { link = "UdagawanightOrange" },
    luaIn = { link = "UdagawanightRed" },
    luaFunction = { link = "UdagawanightAqua" },
    luaTable = { link = "UdagawanightOrange" },
    moonSpecialOp = { link = "UdagawanightFg3" },
    moonExtendedOp = { link = "UdagawanightFg3" },
    moonFunction = { link = "UdagawanightFg3" },
    moonObject = { link = "UdagawanightYellow" },
    javaAnnotation = { link = "UdagawanightBlue" },
    javaDocTags = { link = "UdagawanightAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "UdagawanightFg3" },
    javaParen1 = { link = "UdagawanightFg3" },
    javaParen2 = { link = "UdagawanightFg3" },
    javaParen3 = { link = "UdagawanightFg3" },
    javaParen4 = { link = "UdagawanightFg3" },
    javaParen5 = { link = "UdagawanightFg3" },
    javaOperator = { link = "UdagawanightOrange" },
    javaVarArg = { link = "UdagawanightGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "UdagawanightGreen" },
    elixirInterpolationDelimiter = { link = "UdagawanightAqua" },
    elixirModuleDeclaration = { link = "UdagawanightYellow" },
    scalaNameDefinition = { link = "UdagawanightFg1" },
    scalaCaseFollowing = { link = "UdagawanightFg1" },
    scalaCapitalWord = { link = "UdagawanightFg1" },
    scalaTypeExtension = { link = "UdagawanightFg1" },
    scalaKeyword = { link = "UdagawanightRed" },
    scalaKeywordModifier = { link = "UdagawanightRed" },
    scalaSpecial = { link = "UdagawanightAqua" },
    scalaOperator = { link = "UdagawanightFg1" },
    scalaTypeDeclaration = { link = "UdagawanightYellow" },
    scalaTypeTypePostDeclaration = { link = "UdagawanightYellow" },
    scalaInstanceDeclaration = { link = "UdagawanightFg1" },
    scalaInterpolation = { link = "UdagawanightAqua" },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "UdagawanightGreenBold" },
    markdownH2 = { link = "UdagawanightGreenBold" },
    markdownH3 = { link = "UdagawanightYellowBold" },
    markdownH4 = { link = "UdagawanightYellowBold" },
    markdownH5 = { link = "UdagawanightYellow" },
    markdownH6 = { link = "UdagawanightYellow" },
    markdownCode = { link = "UdagawanightAqua" },
    markdownCodeBlock = { link = "UdagawanightAqua" },
    markdownCodeDelimiter = { link = "UdagawanightAqua" },
    markdownBlockquote = { link = "UdagawanightGray" },
    markdownListMarker = { link = "UdagawanightGray" },
    markdownOrderedListMarker = { link = "UdagawanightGray" },
    markdownRule = { link = "UdagawanightGray" },
    markdownHeadingRule = { link = "UdagawanightGray" },
    markdownUrlDelimiter = { link = "UdagawanightFg3" },
    markdownLinkDelimiter = { link = "UdagawanightFg3" },
    markdownLinkTextDelimiter = { link = "UdagawanightFg3" },
    markdownHeadingDelimiter = { link = "UdagawanightOrange" },
    markdownUrl = { link = "UdagawanightPurple" },
    markdownUrlTitleDelimiter = { link = "UdagawanightGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "UdagawanightBlue" },
    haskellIdentifier = { link = "UdagawanightAqua" },
    haskellSeparator = { link = "UdagawanightFg4" },
    haskellDelimiter = { link = "UdagawanightOrange" },
    haskellOperators = { link = "UdagawanightPurple" },
    haskellBacktick = { link = "UdagawanightOrange" },
    haskellStatement = { link = "UdagawanightPurple" },
    haskellConditional = { link = "UdagawanightPurple" },
    haskellLet = { link = "UdagawanightRed" },
    haskellDefault = { link = "UdagawanightRed" },
    haskellWhere = { link = "UdagawanightRed" },
    haskellBottom = { link = "UdagawanightRedBold" },
    haskellImportKeywords = { link = "UdagawanightPurpleBold" },
    haskellDeclKeyword = { link = "UdagawanightOrange" },
    haskellDecl = { link = "UdagawanightOrange" },
    haskellDeriving = { link = "UdagawanightPurple" },
    haskellAssocType = { link = "UdagawanightAqua" },
    haskellNumber = { link = "UdagawanightAqua" },
    haskellPragma = { link = "UdagawanightRedBold" },
    haskellTH = { link = "UdagawanightAquaBold" },
    haskellForeignKeywords = { link = "UdagawanightGreen" },
    haskellKeyword = { link = "UdagawanightRed" },
    haskellFloat = { link = "UdagawanightAqua" },
    haskellInfix = { link = "UdagawanightPurple" },
    haskellQuote = { link = "UdagawanightGreenBold" },
    haskellShebang = { link = "UdagawanightYellowBold" },
    haskellLiquid = { link = "UdagawanightPurpleBold" },
    haskellQuasiQuoted = { link = "UdagawanightBlueBold" },
    haskellRecursiveDo = { link = "UdagawanightPurple" },
    haskellQuotedType = { link = "UdagawanightRed" },
    haskellPreProc = { link = "UdagawanightFg4" },
    haskellTypeRoles = { link = "UdagawanightRedBold" },
    haskellTypeForall = { link = "UdagawanightRed" },
    haskellPatternKeyword = { link = "UdagawanightBlue" },
    jsonKeyword = { link = "UdagawanightGreen" },
    jsonQuote = { link = "UdagawanightGreen" },
    jsonBraces = { link = "UdagawanightFg1" },
    jsonString = { link = "UdagawanightFg1" },
    mailQuoted1 = { link = "UdagawanightAqua" },
    mailQuoted2 = { link = "UdagawanightPurple" },
    mailQuoted3 = { link = "UdagawanightYellow" },
    mailQuoted4 = { link = "UdagawanightGreen" },
    mailQuoted5 = { link = "UdagawanightRed" },
    mailQuoted6 = { link = "UdagawanightOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "UdagawanightFg1" },
    csEndColon = { link = "UdagawanightFg1" },
    csLogicSymbols = { link = "UdagawanightFg1" },
    csParens = { link = "UdagawanightFg3" },
    csOpSymbols = { link = "UdagawanightFg3" },
    csInterpolationDelimiter = { link = "UdagawanightFg3" },
    csInterpolationAlignDel = { link = "UdagawanightAquaBold" },
    csInterpolationFormat = { link = "UdagawanightAqua" },
    csInterpolationFormatDel = { link = "UdagawanightAquaBold" },
    rustSigil = { link = "UdagawanightOrange" },
    rustEscape = { link = "UdagawanightAqua" },
    rustStringContinuation = { link = "UdagawanightAqua" },
    rustEnum = { link = "UdagawanightAqua" },
    rustStructure = { link = "UdagawanightAqua" },
    rustModPathSep = { link = "UdagawanightFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "UdagawanightAqua" },
    ocamlOperator = { link = "UdagawanightFg1" },
    ocamlKeyChar = { link = "UdagawanightOrange" },
    ocamlArrow = { link = "UdagawanightOrange" },
    ocamlInfixOpKeyword = { link = "UdagawanightRed" },
    ocamlConstructor = { link = "UdagawanightOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "UdagawanightFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "UdagawanightFg1" },
    LspSagaAutoPreview = { link = "UdagawanightOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "UdagawanightAqua" },
    LspSagaDefPreviewBorder = { link = "UdagawanightBlue" },
    LspSagaHoverBorder = { link = "UdagawanightOrange" },
    LspSagaRenameBorder = { link = "UdagawanightBlue" },
    LspSagaDiagnosticSource = { link = "UdagawanightOrange" },
    LspSagaDiagnosticBorder = { link = "UdagawanightPurple" },
    LspSagaDiagnosticHeader = { link = "UdagawanightGreen" },
    LspSagaSignatureHelpBorder = { link = "UdagawanightGreen" },
    SagaShadow = { link = "UdagawanightBg0" },
    DashboardShortCut = { link = "UdagawanightOrange" },
    DashboardHeader = { link = "UdagawanightAqua" },
    DashboardCenter = { link = "UdagawanightYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "UdagawanightAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg4 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg4 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "UdagawanightFg1" },
    CarbonExe = { link = "UdagawanightYellow" },
    CarbonSymlink = { link = "UdagawanightAqua" },
    CarbonBrokenSymlink = { link = "UdagawanightRed" },
    CarbonIndicator = { link = "UdagawanightGray" },
    CarbonDanger = { link = "UdagawanightRed" },
    CarbonPending = { link = "UdagawanightYellow" },
    NoiceCursor = { link = "TermCursor" },
    NoiceCmdlinePopupBorder = { fg = colors.blue, bg = nil },
    NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
    NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderSearch = { fg = colors.yellow, bg = nil },
    NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
    NotifyDEBUGBorder = { link = "UdagawanightBlue" },
    NotifyDEBUGIcon = { link = "UdagawanightBlue" },
    NotifyDEBUGTitle = { link = "UdagawanightBlue" },
    NotifyERRORBorder = { link = "UdagawanightRed" },
    NotifyERRORIcon = { link = "UdagawanightRed" },
    NotifyERRORTitle = { link = "UdagawanightRed" },
    NotifyINFOBorder = { link = "UdagawanightAqua" },
    NotifyINFOIcon = { link = "UdagawanightAqua" },
    NotifyINFOTitle = { link = "UdagawanightAqua" },
    NotifyTRACEBorder = { link = "UdagawanightGreen" },
    NotifyTRACEIcon = { link = "UdagawanightGreen" },
    NotifyTRACETitle = { link = "UdagawanightGreen" },
    NotifyWARNBorder = { link = "UdagawanightYellow" },
    NotifyWARNIcon = { link = "UdagawanightYellow" },
    NotifyWARNTitle = { link = "UdagawanightYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.aqua },
    RainbowDelimiterRed = { fg = colors.red },
    RainbowDelimiterOrange = { fg = colors.orange },
    RainbowDelimiterYellow = { fg = colors.yellow },
    RainbowDelimiterGreen = { fg = colors.green },
    RainbowDelimiterBlue = { fg = colors.blue },
    RainbowDelimiterViolet = { fg = colors.purple },
    RainbowDelimiterCyan = { fg = colors.aqua },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "UdagawanightYellow" },
    DapUIBreakpointsDisabledLine = { link = "UdagawanightGray" },
    DapUIBreakpointsInfo = { link = "UdagawanightAqua" },
    DapUIBreakpointsLine = { link = "UdagawanightYellow" },
    DapUIBreakpointsPath = { link = "UdagawanightBlue" },
    DapUICurrentFrameName = { link = "UdagawanightPurple" },
    DapUIDecoration = { link = "UdagawanightPurple" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "UdagawanightAqua" },
    DapUILineNumber = { link = "UdagawanightYellow" },
    DapUIModifiedValue = { link = "UdagawanightRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "UdagawanightBlue" },
    DapUISource = { link = "UdagawanightFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "UdagawanightBlue" },
    DapUIThread = { link = "UdagawanightBlue" },
    DapUIType = { link = "UdagawanightOrange" },
    DapUIUnavailable = { link = "UdagawanightGray" },
    DapUIWatchesEmpty = { link = "UdagawanightGray" },
    DapUIWatchesError = { link = "UdagawanightRed" },
    DapUIWatchesValue = { link = "UdagawanightYellow" },
    DapUIWinSelect = { link = "UdagawanightYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "UdagawanightGreenBold" },
    DiffviewFilePanelInsertions = { link = "UdagawanightGreenBold" },
    DiffviewFilePanelDeletions = { link = "UdagawanightRedBold" },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = colors.fg1, bg = colors.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "UdagawanightGreen" },
    MiniDepsChangeRemoved = { link = "UdagawanightRed" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "UdagawanightGreen" },
    MiniDiffSignChange = { link = "UdagawanightAqua" },
    MiniDiffSignDelete = { link = "UdagawanightRed" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = colors.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "UdagawanightFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "UdagawanightOrangeBold" },
    MiniHipatternsFixme = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniHipatternsHack = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniHipatternsNote = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniHipatternsTodo = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniIconsAzure = { link = "UdagawanightBlue" },
    MiniIconsBlue = { link = "UdagawanightBlue" },
    MiniIconsCyan = { link = "UdagawanightAqua" },
    MiniIconsGreen = { link = "UdagawanightGreen" },
    MiniIconsGrey = { link = "UdagawanightFg0" },
    MiniIconsOrange = { link = "UdagawanightOrange" },
    MiniIconsPurple = { link = "UdagawanightPurple" },
    MiniIconsRed = { link = "UdagawanightRed" },
    MiniIconsYellow = { link = "UdagawanightYellow" },
    MiniIndentscopeSymbol = { link = "UdagawanightGray" },
    MiniIndentscopeSymbolOff = { link = "UdagawanightYellow" },
    MiniJump = { link = "UdagawanightOrangeUnderline" },
    MiniJump2dDim = { link = "UdagawanightGray" },
    MiniJump2dSpot = { fg = colors.orange, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { fg = colors.aqua, bg = colors.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = colors.yellow, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { bg = colors.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "UdagawanightGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    MiniStatuslineModeInsert = { fg = colors.bg0, bg = colors.blue, bold = config.bold },
    MiniStatuslineModeNormal = { fg = colors.bg0, bg = colors.fg1, bold = config.bold },
    MiniStatuslineModeOther = { fg = colors.bg0, bg = colors.aqua, bold = config.bold },
    MiniStatuslineModeReplace = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MiniStatuslineModeVisual = { fg = colors.bg0, bg = colors.green, bold = config.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = colors.green, bg = colors.bg1, bold = config.bold, reverse = config.invert_tabline },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTablineModifiedCurrent = {
      fg = colors.bg1,
      bg = colors.green,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineModifiedHidden = { fg = colors.bg1, bg = colors.bg4, reverse = config.invert_tabline },
    MiniTablineModifiedVisible = { fg = colors.bg1, bg = colors.fg1, reverse = config.invert_tabline },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = colors.fg1, bg = colors.bg1, reverse = config.invert_tabline },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "UdagawanightRedBold" },
    MiniTestPass = { link = "UdagawanightGreenBold" },
    MiniTrailspace = { bg = colors.red },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "UdagawanightRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "UdagawanightFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "UdagawanightFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "UdagawanightGreen" },
    ["@markup.list.unchecked"] = { link = "UdagawanightGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "UdagawanightFg1" },
    ["@namespace"] = { link = "UdagawanightFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "UdagawanightFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "UdagawanightGreen" },
    ["@text.todo.unchecked"] = { link = "UdagawanightGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config UdagawanightConfig?
Udagawanight.setup = function(config)
  Udagawanight.config = vim.tbl_deep_extend("force", Udagawanight.config, config or {})
end

--- main load function
Udagawanight.load = function()
  if vim.version().minor < 8 then
    vim.notify_once("udagawanight.nvim: you must use neovim 0.8 or higher")
    return
  end

  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "udagawanight"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Udagawanight
